In [57]:
pip install tensorflow-gpu

^C
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "C:\Users\gupta\AppData\Roaming\Python\Python311\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gupta\AppData\Roaming\Python\Python311\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gupta\AppData\Roaming\Python\Python311\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^

Defaulting to user installation because normal site-packages is not writeable
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


In [83]:
!pip install pandas matplotlib sklearn


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\gupta\anaconda3\python.exe -m pip install --upgrade pip


In [84]:
import os
import pandas as pd 
import tensorflow as tf
import numpy as np

In [85]:
os.path.join('jigsaw-toxic-comment-classification-challenge', 'train.csv','train.csv')

'jigsaw-toxic-comment-classification-challenge\\train.csv\\train.csv'

In [86]:
df = pd.read_csv(
    os.path.join('jigsaw-toxic-comment-classification-challenge', 'train.csv','train.csv')
)

In [87]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\r\nWhy the edits made under my use...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\r\nMore\r\nI can't make any real suggestions...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [88]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \r\n\r\nThat...   
159568  ffee36eab5c267c9  Spitzer \r\n\r\nUmm, theres no actual article ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\r\nAnd ... I really don't think you understa...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [89]:
df.iloc[1]['comment_text']

"D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)"

In [90]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [91]:
df[df.columns[2:]].iloc[3]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 3, dtype: int64

In [92]:
!pip list


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\gupta\anaconda3\python.exe -m pip install --upgrade pip


Package                       Version
----------------------------- ---------------
absl-py                       2.0.0
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
albumentations                1.3.1
altair                        5.2.0
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
annotated-types               0.6.0
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
astunparse

In [93]:
from tensorflow.keras.layers import TextVectorization

In [94]:
TextVectorization??

Init signature:
TextVectorization(
    max_tokens=None,
    standardize='lower_and_strip_punctuation',
    split='whitespace',
    ngrams=None,
    output_mode='int',
    output_sequence_length=None,
    pad_to_max_tokens=False,
    vocabulary=None,
    idf_weights=None,
    sparse=False,
    ragged=False,
    encoding='utf-8',
    **kwargs,
)
Source:        
@keras_export(
    "keras.layers.TextVectorization",
    "keras.layers.experimental.preprocessing.TextVectorization",
    v1=[],
)
class TextVectorization(base_preprocessing_layer.PreprocessingLayer):
    """A preprocessing layer which maps text features to integer sequences.

    This layer has basic options for managing text in a Keras model. It
    transforms a batch of strings (one example = one string) into either a list
    of token indices (one example = 1D tensor of integer token indices) or a
    dense representation (one example = 1D tensor of float values representing
    data about the example's tokens). This layer is 

In [95]:
X = df['comment_text']
Y = df[df.columns[2:]].values

In [96]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [97]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [98]:
Y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [99]:
X

0         Explanation\r\nWhy the edits made under my use...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\r\nMore\r\nI can't make any real suggestions...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \r\n\r\nThat...
159568    Spitzer \r\n\r\nUmm, theres no actual article ...
159569    And it looks like it was actually you who put ...
159570    "\r\nAnd ... I really don't think you understa...
Name: comment_text, Length: 159571, dtype: object

In [100]:
Max_words = 100000  #these are the number of words in our vocab or the dictionary which are going to be tokenized i.e. mapped to numbers or integers.

In [101]:
Vectorizer = TextVectorization(max_tokens =Max_words,
                               output_sequence_length = 1000,    #how long that comment's range go to 
                               output_mode = 'int')    #this specifies that each word is mapped to an integer

In [102]:
type(X)    # its a pandas series.its just a file format.its effectively a single column out of a pandas dataset.

pandas.core.series.Series

In [103]:
X.values

array(["Explanation\r\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Spitzer \r\n\r\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.',
       'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.',
       '"\r\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of 

In [104]:
type(X.values)

numpy.ndarray

In [105]:
Vectorizer.adapt(X.values)  # we are teaching our Vectorizer our vocabulary i.e it learns each word which are present in our toxic comments.

In [106]:
Vectorizer('Hi,life is just awesome!')      # this actually strips out punctuations. i.e is does not map punctuations into numbers.basically removes them.  

<tf.Tensor: shape=(1000,), dtype=int64, numpy=
array([   1,    9,   51, 3205,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    

In [107]:
Vectorizer('Hi,life is just awesome!')[:5]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([   1,    9,   51, 3205,    0], dtype=int64)>

In [108]:
vectorized_text = Vectorizer(X.values)    #its actually tokenizing the dataset

In [109]:
len(X)

159571

In [110]:
vectorized_text      # there are 159571 samples of comments here and we have intentionally limit our range to 1900 words for each comments/sentence.....if it exceeds that,then it maps all of them to zero.

<tf.Tensor: shape=(159571, 1000), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [111]:
#MCSHBAP - map , cache , shuffle ,batch ,prefetch 
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text , Y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)     #all four are data preprocessing steps. 
dataset = dataset.batch(12)
daatset = dataset.prefetch(8)     #helps bottlenecks


In [112]:
 batch_X ,batch_y = dataset.as_numpy_iterator().next()

In [113]:
 batch_X     #vectorized text examples

array([[   86,   655,    46, ...,     0,     0,     0],
       [    1,     9,  1081, ...,     0,     0,     0],
       [   57,  1396,    13, ...,     0,     0,     0],
       ...,
       [   49,   234,     8, ...,     0,     0,     0],
       [ 5078, 17533,   424, ...,     0,     0,     0],
       [  410,     2,  4940, ...,     0,     0,     0]], dtype=int64)

In [114]:
batch_X.shape  # thus we can see here is that there are 16 samples in batch with words each containing restricted to 1500 words

(12, 1000)

In [115]:
batch_y.shape   # 6 here represents that we have got 6 values in each of the vectors.

(12, 6)

In [116]:
len(dataset)    # this 9974 are the number of batches and not the number of samples. Each batch contains 16 samples.

13298

In [117]:
int(len(dataset)*.7)

9308

In [118]:
train = dataset.take(int(len(dataset)*.7))         # .take method will basically grab or take that partition of data out and assign it to a variable .Here we have taken out 70 per. 6981 batches are being trained and convert it into an integer.

In [119]:
validation_partition = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))    # we are going to skip 70 per of data and grab 20 per only.

In [120]:
test_partition = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))    

In [121]:
len(train)   # 6981 batches 

9308

In [122]:
len(validation_partition )   #1994 batches

2659

In [123]:
len(test_partition)      # 997 batches

1329

In [124]:
train_generator = train.as_numpy_iterator()
train_generator.next()         #using this .next() , it is going to next batch .

(array([[  637,    61,    33, ...,     0,     0,     0],
        [    2, 17374,  1137, ...,     0,     0,     0],
        [  191,   288,     1, ...,     0,     0,     0],
        ...,
        [  125,     8,   525, ...,     0,     0,     0],
        [    8,    19,   164, ...,     0,     0,     0],
        [ 1530,  1798,  7301, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 0]], dtype=int64))

In [125]:
from tensorflow.keras.models import Sequential


In [126]:
from tensorflow.keras.layers import LSTM , Dropout, Bidirectional , Dense , Embedding

In [127]:
model = Sequential()      #this is going to instantiate the model. it is basically going to instantiate the sequential api.we can then add the number of layers to the model  to be abble to build it up.
model.add(Embedding(Max_words+1 , 32))     # creating the embedding layer.

In [128]:
model.add(Bidirectional(LSTM( 32 , activation='tanh')))       #Bidirectional LSTM layer
model.add(Dense(128 , activation='relu' ))           
model.add(Dense(256 , activation='relu'))                 #Feature extractor or fully connected layers.
model.add(Dense(128 , activation='relu' ))
model.add(Dense(6 , activation = 'sigmoid'))            #Final layer.This final layer maps to the number of output that we have got inside of out neural network.


In [129]:
model.compile(loss ='BinaryCrossentropy' , optimizer = 'Adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 32)          3200032   
                                                                 
 bidirectional_1 (Bidirecti  (None, 64)                16640     
 onal)                                                           
                                                                 
 dense_4 (Dense)             (None, 128)               8320      
                                                                 
 dense_5 (Dense)             (None, 256)               33024     
                                                                 
 dense_6 (Dense)             (None, 128)               32896     
                                                                 
 dense_7 (Dense)             (None, 6)                 774       
                                                      

In [ ]:
history = model.fit( train , epochs= 6 ,validation_data = validation_partition)

Epoch 1/6


9308/9308 [==============================] - 3091s 332ms/step - loss: 0.0635 - val_loss: 0.0480
Epoch 2/6
9308/9308 [==============================] - 3502s 376ms/step - loss: 0.0454 - val_loss: 0.0419
Epoch 3/6
9308/9308 [==============================] - 3135s 337ms/step - loss: 0.0415 - val_loss: 0.0370
Epoch 4/6
9308/9308 [==============================] - 3279s 352ms/step - loss: 0.0370 - val_loss: 0.0331
Epoch 5/6
9308/9308 [==============================] - 3080s 331ms/step - loss: 0.0337 - val_loss: 0.0304
Epoch 6/6
9308/9308 [==============================] - 2975s 320ms/step - loss: 0.0304 - val_loss: 0.0261


In [130]:
history.history

{'loss': [0.06347429007291794,
  0.045432526618242264,
  0.04152722284197807,
  0.037002354860305786,
  0.033666957169771194,
  0.03044562228024006],
 'val_loss': [0.04802641645073891,
  0.04190870001912117,
  0.037009961903095245,
  0.03312709927558899,
  0.03042571060359478,
  0.026127569377422333]}

In [58]:
from matplotlib import pyplot as plt

In [59]:
plt.figure(figsize =( 8 ,5 ))
pd.DataFrame(history.history).plot
plt.show()

<Figure size 800x500 with 0 Axes>

In [60]:
batch = test_partition.as_numpy_iterator().next()

In [61]:
input_text = Vectorizer('you freaking suck!')


In [62]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

model.predict(input_text)             # here we will getting error because here we are passing a single text field..and not a batch or a sequel or a series of valules.thats why we are getting error here.

In [63]:
model.predict(np.array([input_text]))

1/1 [==============================] - 1s 888ms/step


array([[0.9985017 , 0.31909883, 0.97026867, 0.05371985, 0.7502765 ,
        0.06868541]], dtype=float32)

In [64]:
np.expand_dims( input_text , 0 )        #this does the same thing, but it does it cleanly.

array([[   7, 7158,  397,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [65]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [66]:
model.predict(np.expand_dims(input_text , 0))     #here we can see that 0.986 means that since its above 0.5 thus it is 'toxic' , 0.822 also means its 'obscene'   

1/1 [==============================] - 0s 60ms/step


array([[0.9985017 , 0.31909883, 0.97026867, 0.05371985, 0.7502765 ,
        0.06868541]], dtype=float32)

In [67]:
from tensorflow.keras.metrics import Precision ,Recall ,CategoricalAccuracy


In [68]:
pre= Precision()         #here we have instantiated our precision metrics.
re = Recall()                          #similarly here also
acc = CategoricalAccuracy()            #here also

In [69]:
for batch in test_partition.as_numpy_iterator():       #basically it loops through each and every single batch of our data pipeline 
     #unpacking the batch
     X_true , Y_true = batch
     
     #Make a prediction
     yhat = model.predict(X_true )
     
     #Flatten the predictions 
     Y_true = Y_true.flatten()
     yhat = yhat.flatten()
     
     pre.update_state(Y_true , yhat)
     re.update_state(Y_true , yhat)
     acc.update_state(Y_true , yhat)
    

1/1 [==============================] - 0s 78ms/step


In [70]:
print(f'Precision : {pre.result().numpy()} , Recall:{re.result().numpy()} , Accuracy :{acc.result().numpy()}')

Precision : 0.8913043737411499 , Recall:0.8355505466461182 , Accuracy :0.49962377548217773


In [71]:
!pip install gradio jinja2


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\gupta\anaconda3\python.exe -m pip install --upgrade pip


In [72]:
pip install gradio

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [73]:
import tensorflow as tf
import gradio as gr

In [74]:
model.save('toxicity.h5')

C:\Users\gupta\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [75]:
model = tf.keras.models.load_model('toxicity.h5')

In [76]:
input_str = Vectorizer(' hey! i freaken hate you ! ')
res = model.predict(np.expand_dims(input_str, 0 ))

1/1 [==============================] - 1s 593ms/step


In [77]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [78]:
res

array([[0.8472727 , 0.01911537, 0.13164602, 0.10382161, 0.46514973,
        0.21756554]], dtype=float32)

In [79]:
def score_comment(comment):
    vectorized_comment = Vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [80]:
interface = gr.Interface(fn=score_comment ,
                         inputs=gr.Textbox(lines=2, placeholder='Comment to score') , 
                        outputs='text')

In [82]:
interface.launch(share=True)


Rerunning server... use `close()` to stop if you need to change `launch()` parameters.
----
Running on public URL: https://2460b54f1126e42a5a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


1/1 [==============================] - 0s 42ms/step
